### ISSUE TITLE
RoomReverb vst3 in Reaper DAW - sound issue when rendering or switching plugin offline/online.

### ISSUE THREAD

**Issue by veksha** [zazz84/zazzVSTPlugins#1]
issues happens on rendering!
also when switching plugin offline/online.

issue1: reverb is not the same as it was before (can't hear it working). 
issue2: also sometimes only left channel is playing and right channel is muted. (dry and wet signal is fully muted on right channel).

video shows only issue1:

https://github.com/user-attachments/assets/0752a460-bc61-489f-a618-212f2401efac

maybe issue2 will be gone with fixing issue1.

**Comment by veksha** [comment]
for now i use a workaround. to render my song correctly i use the following render options:
(online render + uncheck "mix and process at proj samplerate..")

![image](https://github.com/user-attachments/assets/a89ff04e-36c0-4d02-ad2b-31b1484822bf)

**Comment by zazz84** [comment]
Hi,
Thanks for reporting! Hope it is fixed on 1.0.2 version (https://www.kvraudio.com/product/room-reverb-by-zazz)

**Comment by veksha** [comment]
Thanks! seems working good now. great plugin!
